import "./globals.css";
import type { Metadata } from "next";

import localFont from "next/font/local";

export const proto = localFont({
  src: "../assets/fonts/proto-mono-regular.woff2",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={proto.className}>
        {/* <Nav /> */}
        {children}
      </body>
    </html>
  );
}
